CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;
ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `TB_COMUNIDADE` (
    `ID_COMUNIDADE` int NOT NULL AUTO_INCREMENT,
    `NOME` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `DESCRICAO` longtext CHARACTER SET utf8mb4 NULL,
    `DATA_CRIACAO` datetime(6) NOT NULL,
    CONSTRAINT `PK_TB_COMUNIDADE` PRIMARY KEY (`ID_COMUNIDADE`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_ROLE` (
    `ID_ROLE` int NOT NULL AUTO_INCREMENT,
    `NOME` varchar(256) CHARACTER SET utf8mb4 NULL,
    `NORMALIZED_NOME` varchar(256) CHARACTER SET utf8mb4 NULL,
    `CONCURRENCY_STAMP` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_ROLE` PRIMARY KEY (`ID_ROLE`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USUARIO` (
    `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
    `NOME` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `EMAIL` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `SENHA_HASH` longtext CHARACTER SET utf8mb4 NULL,
    `DATA_CADASTRO` datetime(6) NOT NULL,
    `TIPO_USUARIO` varchar(50) CHARACTER SET utf8mb4 NULL,
    `AREA_ESTUDO` varchar(200) CHARACTER SET utf8mb4 NULL,
    `TRILHA_CONHECIMENTO` varchar(500) CHARACTER SET utf8mb4 NULL,
    `PROJETOS` varchar(1000) CHARACTER SET utf8mb4 NULL,
    `USERNAME` varchar(150) CHARACTER SET utf8mb4 NULL,
    `NORMALIZED_USERNAME` varchar(150) CHARACTER SET utf8mb4 NULL,
    `NORMALIZED_EMAIL` varchar(150) CHARACTER SET utf8mb4 NULL,
    `EMAIL_CONFIRMED` tinyint(1) NOT NULL,
    `SECURITY_STAMP` longtext CHARACTER SET utf8mb4 NULL,
    `CONCURRENCY_STAMP` longtext CHARACTER SET utf8mb4 NULL,
    `TELEFONE` longtext CHARACTER SET utf8mb4 NULL,
    `TELEFONE_CONFIRMADO` tinyint(1) NOT NULL,
    `DOIS_FATORES_ATIVADO` tinyint(1) NOT NULL,
    `BLOQUEIO_FIM` datetime(6) NULL,
    `BLOQUEIO_ATIVADO` tinyint(1) NOT NULL,
    `FALHAS_ACESSO` int NOT NULL,
    CONSTRAINT `PK_TB_USUARIO` PRIMARY KEY (`ID_USUARIO`)
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_GRUPO_ESTUDO` (
    `ID_GRUPO` int NOT NULL AUTO_INCREMENT,
    `NOME` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `DESCRICAO` longtext CHARACTER SET utf8mb4 NULL,
    `FK_COMUNIDADE` int NULL,
    `DATA_CRIACAO` datetime(6) NOT NULL,
    CONSTRAINT `PK_TB_GRUPO_ESTUDO` PRIMARY KEY (`ID_GRUPO`),
    CONSTRAINT `FK_GRUPO_COMUNIDADE` FOREIGN KEY (`FK_COMUNIDADE`) REFERENCES `TB_COMUNIDADE` (`ID_COMUNIDADE`) ON DELETE SET NULL
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_ROLE_CLAIM` (
    `ID_ROLE_CLAIM` int NOT NULL AUTO_INCREMENT,
    `FK_ROLE` int NOT NULL,
    `ClaimType` longtext CHARACTER SET utf8mb4 NULL,
    `ClaimValue` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_ROLE_CLAIM` PRIMARY KEY (`ID_ROLE_CLAIM`),
    CONSTRAINT `FK_TB_ROLE_CLAIM_TB_ROLE_FK_ROLE` FOREIGN KEY (`FK_ROLE`) REFERENCES `TB_ROLE` (`ID_ROLE`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_LISTA_LEITURA` (
    `ID_LISTA` int NOT NULL AUTO_INCREMENT,
    `NOME` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `DESCRICAO` longtext CHARACTER SET utf8mb4 NULL,
    `FK_USUARIO` int NOT NULL,
    CONSTRAINT `PK_TB_LISTA_LEITURA` PRIMARY KEY (`ID_LISTA`),
    CONSTRAINT `FK_LISTA_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_MATERIAL` (
    `ID_MATERIAL` int NOT NULL AUTO_INCREMENT,
    `TITULO` varchar(250) CHARACTER SET utf8mb4 NOT NULL,
    `DESCRICAO` longtext CHARACTER SET utf8mb4 NULL,
    `TIPO` varchar(50) CHARACTER SET utf8mb4 NULL,
    `CAMINHOIMG` varchar(250) CHARACTER SET utf8mb4 NULL,
    `FK_USUARIO_CRIADOR` int NOT NULL,
    `DATA_CRIACAO` datetime(6) NOT NULL,
    `STATUS` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_MATERIAL` PRIMARY KEY (`ID_MATERIAL`),
    CONSTRAINT `FK_MATERIAL_USUARIO` FOREIGN KEY (`FK_USUARIO_CRIADOR`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE RESTRICT
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USER_CLAIM` (
    `ID_CLAIM` int NOT NULL AUTO_INCREMENT,
    `FK_USUARIO` int NOT NULL,
    `ClaimType` longtext CHARACTER SET utf8mb4 NULL,
    `ClaimValue` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_USER_CLAIM` PRIMARY KEY (`ID_CLAIM`),
    CONSTRAINT `FK_TB_USER_CLAIM_TB_USUARIO_FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USER_LOGIN` (
    `LoginProvider` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `ProviderKey` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `ProviderDisplayName` longtext CHARACTER SET utf8mb4 NULL,
    `FK_USUARIO` int NOT NULL,
    CONSTRAINT `PK_TB_USER_LOGIN` PRIMARY KEY (`LoginProvider`, `ProviderKey`),
    CONSTRAINT `FK_TB_USER_LOGIN_TB_USUARIO_FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USER_ROLE` (
    `FK_USUARIO` int NOT NULL,
    `FK_ROLE` int NOT NULL,
    CONSTRAINT `PK_TB_USER_ROLE` PRIMARY KEY (`FK_USUARIO`, `FK_ROLE`),
    CONSTRAINT `FK_TB_USER_ROLE_TB_ROLE_FK_ROLE` FOREIGN KEY (`FK_ROLE`) REFERENCES `TB_ROLE` (`ID_ROLE`) ON DELETE CASCADE,
    CONSTRAINT `FK_TB_USER_ROLE_TB_USUARIO_FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USER_TOKEN` (
    `FK_USUARIO` int NOT NULL,
    `LoginProvider` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Name` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `Value` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_USER_TOKEN` PRIMARY KEY (`FK_USUARIO`, `LoginProvider`, `Name`),
    CONSTRAINT `FK_TB_USER_TOKEN_TB_USUARIO_FK_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USUARIO_COMUNIDADE` (
    `FK_USUARIO` int NOT NULL,
    `FK_COMUNIDADE` int NOT NULL,
    `DATA_ENTRADA` datetime(6) NOT NULL,
    CONSTRAINT `PK_TB_USUARIO_COMUNIDADE` PRIMARY KEY (`FK_USUARIO`, `FK_COMUNIDADE`),
    CONSTRAINT `FK_USUARIOCOMUNIDADE_COMUNIDADE` FOREIGN KEY (`FK_COMUNIDADE`) REFERENCES `TB_COMUNIDADE` (`ID_COMUNIDADE`) ON DELETE CASCADE,
    CONSTRAINT `FK_USUARIOCOMUNIDADE_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_POSTAGEM` (
    `ID_POSTAGEM` int NOT NULL AUTO_INCREMENT,
    `TITULO` varchar(200) CHARACTER SET utf8mb4 NOT NULL,
    `CONTEUDO` varchar(5000) CHARACTER SET utf8mb4 NOT NULL,
    `DATA_POSTAGEM` datetime(6) NOT NULL,
    `NOFORUMGERAL` tinyint(1) NOT NULL,
    `FK_USUARIO` int NOT NULL,
    `FK_COMUNIDADE` int NULL,
    `FK_GRUPO` int NULL,
    CONSTRAINT `PK_TB_POSTAGEM` PRIMARY KEY (`ID_POSTAGEM`),
    CONSTRAINT `FK_POSTAGEM_COMUNIDADE` FOREIGN KEY (`FK_COMUNIDADE`) REFERENCES `TB_COMUNIDADE` (`ID_COMUNIDADE`) ON DELETE SET NULL,
    CONSTRAINT `FK_POSTAGEM_GRUPO` FOREIGN KEY (`FK_GRUPO`) REFERENCES `TB_GRUPO_ESTUDO` (`ID_GRUPO`) ON DELETE SET NULL,
    CONSTRAINT `FK_POSTAGEM_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_USUARIO_GRUPO` (
    `FK_USUARIO` int NOT NULL,
    `FK_GRUPO` int NOT NULL,
    `DATA_ENTRADA` datetime(6) NOT NULL,
    CONSTRAINT `PK_TB_USUARIO_GRUPO` PRIMARY KEY (`FK_USUARIO`, `FK_GRUPO`),
    CONSTRAINT `FK_USUARIOGRUPO_GRUPO` FOREIGN KEY (`FK_GRUPO`) REFERENCES `TB_GRUPO_ESTUDO` (`ID_GRUPO`) ON DELETE CASCADE,
    CONSTRAINT `FK_USUARIOGRUPO_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_AVALIACAO` (
    `ID_AVALIACAO` int NOT NULL AUTO_INCREMENT,
    `NOTA` int NOT NULL,
    `TIPO_AVALIACAO` varchar(50) CHARACTER SET utf8mb4 NULL,
    `FK_USUARIO` int NOT NULL,
    `FK_MATERIAL` int NOT NULL,
    `RESENHA` longtext CHARACTER SET utf8mb4 NULL,
    CONSTRAINT `PK_TB_AVALIACAO` PRIMARY KEY (`ID_AVALIACAO`),
    CONSTRAINT `FK_AVALIACAO_MATERIAL` FOREIGN KEY (`FK_MATERIAL`) REFERENCES `TB_MATERIAL` (`ID_MATERIAL`) ON DELETE CASCADE,
    CONSTRAINT `FK_AVALIACAO_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_LISTA_TEM_MATERIAL` (
    `FK_LISTA` int NOT NULL,
    `FK_MATERIAL` int NOT NULL,
    `ORDEM` int NULL,
    CONSTRAINT `PK_TB_LISTA_TEM_MATERIAL` PRIMARY KEY (`FK_LISTA`, `FK_MATERIAL`),
    CONSTRAINT `FK_LISTATEMMATERIAL_LISTA` FOREIGN KEY (`FK_LISTA`) REFERENCES `TB_LISTA_LEITURA` (`ID_LISTA`) ON DELETE CASCADE,
    CONSTRAINT `FK_LISTATEMMATERIAL_MATERIAL` FOREIGN KEY (`FK_MATERIAL`) REFERENCES `TB_MATERIAL` (`ID_MATERIAL`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_COMENTARIO` (
    `ID_COMENTARIO` int NOT NULL AUTO_INCREMENT,
    `CONTEUDO` varchar(1000) CHARACTER SET utf8mb4 NOT NULL,
    `DATA_COMENTARIO` datetime(6) NOT NULL,
    `FK_USUARIO` int NOT NULL,
    `FK_POSTAGEM` int NOT NULL,
    `FK_COMENTARIO_PAI` int NULL,
    CONSTRAINT `PK_TB_COMENTARIO` PRIMARY KEY (`ID_COMENTARIO`),
    CONSTRAINT `FK_COMENTARIO_COMENTARIO_PAI` FOREIGN KEY (`FK_COMENTARIO_PAI`) REFERENCES `TB_COMENTARIO` (`ID_COMENTARIO`) ON DELETE RESTRICT,
    CONSTRAINT `FK_COMENTARIO_POSTAGEM` FOREIGN KEY (`FK_POSTAGEM`) REFERENCES `TB_POSTAGEM` (`ID_POSTAGEM`) ON DELETE CASCADE,
    CONSTRAINT `FK_COMENTARIO_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE `TB_COMENTARIO_AVALIACAO` (
    `ID_COMENTARIO_AVALIACAO` int NOT NULL AUTO_INCREMENT,
    `CONTEUDO` varchar(500) CHARACTER SET utf8mb4 NOT NULL,
    `DATA_COMENTARIO` datetime(6) NOT NULL,
    `FK_USUARIO` int NOT NULL,
    `FK_AVALIACAO` int NOT NULL,
    `FK_COMENTARIO_PAI` int NULL,
    CONSTRAINT `PK_TB_COMENTARIO_AVALIACAO` PRIMARY KEY (`ID_COMENTARIO_AVALIACAO`),
    CONSTRAINT `FK_COMENTARIO_AVALIACAO_AVALIACAO` FOREIGN KEY (`FK_AVALIACAO`) REFERENCES `TB_AVALIACAO` (`ID_AVALIACAO`) ON DELETE CASCADE,
    CONSTRAINT `FK_COMENTARIO_AVALIACAO_COMENTARIO_PAI` FOREIGN KEY (`FK_COMENTARIO_PAI`) REFERENCES `TB_COMENTARIO_AVALIACAO` (`ID_COMENTARIO_AVALIACAO`) ON DELETE RESTRICT,
    CONSTRAINT `FK_COMENTARIO_AVALIACAO_USUARIO` FOREIGN KEY (`FK_USUARIO`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE INDEX `IX_TB_AVALIACAO_FK_MATERIAL` ON `TB_AVALIACAO` (`FK_MATERIAL`);

CREATE UNIQUE INDEX `UX_AVALIACAO_USUARIO_MATERIAL` ON `TB_AVALIACAO` (`FK_USUARIO`, `FK_MATERIAL`);

CREATE INDEX `IX_TB_COMENTARIO_FK_COMENTARIO_PAI` ON `TB_COMENTARIO` (`FK_COMENTARIO_PAI`);

CREATE INDEX `IX_TB_COMENTARIO_FK_POSTAGEM` ON `TB_COMENTARIO` (`FK_POSTAGEM`);

CREATE INDEX `IX_TB_COMENTARIO_FK_USUARIO` ON `TB_COMENTARIO` (`FK_USUARIO`);

CREATE INDEX `IX_TB_COMENTARIO_AVALIACAO_FK_AVALIACAO` ON `TB_COMENTARIO_AVALIACAO` (`FK_AVALIACAO`);

CREATE INDEX `IX_TB_COMENTARIO_AVALIACAO_FK_COMENTARIO_PAI` ON `TB_COMENTARIO_AVALIACAO` (`FK_COMENTARIO_PAI`);

CREATE INDEX `IX_TB_COMENTARIO_AVALIACAO_FK_USUARIO` ON `TB_COMENTARIO_AVALIACAO` (`FK_USUARIO`);

CREATE INDEX `IX_TB_GRUPO_ESTUDO_FK_COMUNIDADE` ON `TB_GRUPO_ESTUDO` (`FK_COMUNIDADE`);

CREATE INDEX `IX_TB_LISTA_LEITURA_FK_USUARIO` ON `TB_LISTA_LEITURA` (`FK_USUARIO`);

CREATE INDEX `IX_TB_LISTA_TEM_MATERIAL_FK_MATERIAL` ON `TB_LISTA_TEM_MATERIAL` (`FK_MATERIAL`);

CREATE INDEX `IX_TB_MATERIAL_FK_USUARIO_CRIADOR` ON `TB_MATERIAL` (`FK_USUARIO_CRIADOR`);

CREATE INDEX `IX_TB_POSTAGEM_FK_COMUNIDADE` ON `TB_POSTAGEM` (`FK_COMUNIDADE`);

CREATE INDEX `IX_TB_POSTAGEM_FK_GRUPO` ON `TB_POSTAGEM` (`FK_GRUPO`);

CREATE INDEX `IX_TB_POSTAGEM_FK_USUARIO` ON `TB_POSTAGEM` (`FK_USUARIO`);

CREATE UNIQUE INDEX `RoleNameIndex` ON `TB_ROLE` (`NORMALIZED_NOME`);

CREATE INDEX `IX_TB_ROLE_CLAIM_FK_ROLE` ON `TB_ROLE_CLAIM` (`FK_ROLE`);

CREATE INDEX `IX_TB_USER_CLAIM_FK_USUARIO` ON `TB_USER_CLAIM` (`FK_USUARIO`);

CREATE INDEX `IX_TB_USER_LOGIN_FK_USUARIO` ON `TB_USER_LOGIN` (`FK_USUARIO`);

CREATE INDEX `IX_TB_USER_ROLE_FK_ROLE` ON `TB_USER_ROLE` (`FK_ROLE`);

CREATE INDEX `EmailIndex` ON `TB_USUARIO` (`NORMALIZED_EMAIL`);

CREATE UNIQUE INDEX `UserNameIndex` ON `TB_USUARIO` (`NORMALIZED_USERNAME`);

CREATE UNIQUE INDEX `UX_TB_USUARIO_EMAIL` ON `TB_USUARIO` (`EMAIL`);

CREATE INDEX `IX_TB_USUARIO_COMUNIDADE_FK_COMUNIDADE` ON `TB_USUARIO_COMUNIDADE` (`FK_COMUNIDADE`);

CREATE INDEX `IX_TB_USUARIO_GRUPO_FK_GRUPO` ON `TB_USUARIO_GRUPO` (`FK_GRUPO`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20251119035636_ComentariosAninhados', '9.0.0');

COMMIT;

